language: csharp
mono: none
dotnet: 2.0.0
solution: Training.sln
install:
  - dotnet restore CRUDTest/CRUDTest.csproj
  - dotnet build CRUDTest/CRUDTest.csproj
script: dotnet test CRUDTest/CRUDTest.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
after_success:
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "/home/travis/build/jackyruslymoonlay/CRUD/CRUDTest/coverage.info"